=== JTRosemann/space-meet/server/src/game-schema.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "Space-Meet Game Config",
    "type": "object",
        
    "properties": {        
        "width": {
            "type": "number"
        },
        "height": {
            "type": "number"
        },
        "std_mv_speed": {
            "type": "number"
        },
        "std_trn_speed": {
            "type": "number"
        },
        "std_rad": {
            "type": "number"
        },
        "std_step": {
            "type": "number"
        },
        "players": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "pos_x": {
                        "type": "number"
                    },
                    "pos_y": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "rsrc": {
                        "type": "string"
                    },
                    "rsrc-url": {
                        "type": "string"
                    }
                },
                "required": ["pos_x", "pos_y"],
                "additionalProperties": false
            }
        },
        "podiums": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "pos_x": {
                        "type": "number"
                    },
                    "pos_y": {
                        "type": "number"
                    },
                    "rad": {
                        "type": "number"
                    }
                },
                "required": ["pos_x", "pos_y", "rad"],
                "additionalProperties": false
            }
        },
        "rsrcs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": ["id", "url"],
                "additionalProperties": false
            }
        },
        "$schema": {
            "type": "string"
        }
    },
    "required": ["width", "height"],
    "additionalProperties": false
}

=== JTRosemann/space-meet/server/samples/podium.game.json
{
    "$schema": "../src/game-schema.json",
    "width": 15,
    "height": 10,
    "std_mv_speed": 0.0014,
    "std_trn_speed": 0.0002,
    "std_rad": 0.5,
    "std_step": 0.25,
    "players": [],
    "podiums": [
        {
            "pos_x": 5,
            "pos_y": 5,
            "rad": 2
        }
    ]
}

=== JTRosemann/space-meet/server/samples/lydogo.game.json
{
    "$schema": "../src/game-schema.json",
    "width": 15,
    "height": 10,
    "players": [
        {
            "id": "lynxen",
            "rsrc": "ly",
            "pos_x": 12,
            "pos_y": 3
        },
        {
            "id": "goats",
            "rsrc": "go",
            "pos_x": 12,
            "pos_y": 7
        },
        {
            "id": "dogs",
            "rsrc-url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/08/Alaskan_Huskies_-_Sled_Dogs_-_Ivalo_2013.ogv/Alaskan_Huskies_-_Sled_Dogs_-_Ivalo_2013.ogv.480p.vp9.webm",
            "pos_x": 3,
            "pos_y": 7
        }
    ],
    "rsrcs": [
        {
            "id": "ly",
            "url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Rustende_lynxen_in_bos-Stichting_Natuurbeelden-172347.webm"
        }
        ,
        {
            "id": "go",
            "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/dd/Goats_in_Sunnyvale.webm/Goats_in_Sunnyvale.webm.480p.webm"
        }
    ]
}
